### ISSUE TITLE
Using delta-time instead of ms

### ISSUE THREAD

**Issue by repraze** [cantonjs/claypot-api-plugin#1]
Hi!
I saw you were converting your ms back into sec after using the ms module.
Would you be interested to use my solution https://www.npmjs.com/package/delta-time?
You can provide the scale as a second argument, it would be perfect in your case (src/middlewares/jwt.js).
I know it's a fresh module you have here, so might as well use the fresher things :+1:

**Comment by Cap32** [comment]
No, thanks.
